Search.appendIndex(
    [
                {
            "fqsen": "\\Database\\MyPdo",
            "name": "MyPdo",
            "summary": "Classe\u0020permettant\u0020de\u0020retourner\u0020une\u0020instance\u0020unique\u0020et\u0020configur\u00E9e\u0020de\u0020PDO.",
            "url": "classes/Database-MyPdo.html"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AgetInstance\u0028\u0029",
            "name": "getInstance",
            "summary": "Point\u0020d\u0027acc\u00E8s\u0020\u00E0\u0020l\u0027instance\u0020unique.",
            "url": "classes/Database-MyPdo.html#method_getInstance"
        },                {
            "fqsen": "\\Database\\MyPdo\u003A\u003AsetConfiguration\u0028\u0029",
            "name": "setConfiguration",
            "summary": "Fixer\u0020programmatiquement\u0020la\u0020configuration\u0020de\u0020la\u0020connexion\u0020\u00E0\u0020la\u0020BD.",
            "url": "classes/Database-MyPdo.html#method_setConfiguration"
        },                {
            "fqsen": "\\Entity\\Collection\\EpisodeCollection",
            "name": "EpisodeCollection",
            "summary": "",
            "url": "classes/Entity-Collection-EpisodeCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\EpisodeCollection\u003A\u003AfindBySeasonId\u0028\u0029",
            "name": "findBySeasonId",
            "summary": "",
            "url": "classes/Entity-Collection-EpisodeCollection.html#method_findBySeasonId"
        },                {
            "fqsen": "\\Entity\\Collection\\GenreCollection",
            "name": "GenreCollection",
            "summary": "",
            "url": "classes/Entity-Collection-GenreCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\GenreCollection\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "",
            "url": "classes/Entity-Collection-GenreCollection.html#method_findAll"
        },                {
            "fqsen": "\\Entity\\Collection\\SeasonCollection",
            "name": "SeasonCollection",
            "summary": "",
            "url": "classes/Entity-Collection-SeasonCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\SeasonCollection\u003A\u003AfindByTvShowId\u0028\u0029",
            "name": "findByTvShowId",
            "summary": "",
            "url": "classes/Entity-Collection-SeasonCollection.html#method_findByTvShowId"
        },                {
            "fqsen": "\\Entity\\Collection\\TvShowCollection",
            "name": "TvShowCollection",
            "summary": "",
            "url": "classes/Entity-Collection-TvShowCollection.html"
        },                {
            "fqsen": "\\Entity\\Collection\\TvShowCollection\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "",
            "url": "classes/Entity-Collection-TvShowCollection.html#method_findAll"
        },                {
            "fqsen": "\\Entity\\Collection\\TvShowCollection\u003A\u003AfindbyIdGenre\u0028\u0029",
            "name": "findbyIdGenre",
            "summary": "",
            "url": "classes/Entity-Collection-TvShowCollection.html#method_findbyIdGenre"
        },                {
            "fqsen": "\\Entity\\Episode",
            "name": "Episode",
            "summary": "",
            "url": "classes/Entity-Episode.html"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetSeasonId\u0028\u0029",
            "name": "getSeasonId",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getSeasonId"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003Agetoverview\u0028\u0029",
            "name": "getoverview",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getoverview"
        },                {
            "fqsen": "\\Entity\\Episode\u003A\u003AgetepisodeNumber\u0028\u0029",
            "name": "getepisodeNumber",
            "summary": "",
            "url": "classes/Entity-Episode.html#method_getepisodeNumber"
        },                {
            "fqsen": "\\Entity\\Exception\\EntityNotFoundException",
            "name": "EntityNotFoundException",
            "summary": "",
            "url": "classes/Entity-Exception-EntityNotFoundException.html"
        },                {
            "fqsen": "\\Entity\\Exception\\ParameterException",
            "name": "ParameterException",
            "summary": "",
            "url": "classes/Entity-Exception-ParameterException.html"
        },                {
            "fqsen": "\\Entity\\Exception\\ParameterException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Entity-Exception-ParameterException.html#method___construct"
        },                {
            "fqsen": "\\Entity\\Genre",
            "name": "Genre",
            "summary": "",
            "url": "classes/Entity-Genre.html"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Genre.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Genre\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Genre.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Poster",
            "name": "Poster",
            "summary": "",
            "url": "classes/Entity-Poster.html"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AgetJpeg\u0028\u0029",
            "name": "getJpeg",
            "summary": "",
            "url": "classes/Entity-Poster.html#method_getJpeg"
        },                {
            "fqsen": "\\Entity\\Poster\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "trouve\u0020les\u0020posters\u0020en\u0020fonction\u0020de\u0020l\u0027id",
            "url": "classes/Entity-Poster.html#method_findById"
        },                {
            "fqsen": "\\Entity\\Season",
            "name": "Season",
            "summary": "",
            "url": "classes/Entity-Season.html"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetTvShowId\u0028\u0029",
            "name": "getTvShowId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getTvShowId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getName"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetSeasonNumber\u0028\u0029",
            "name": "getSeasonNumber",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getSeasonNumber"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AgetPosterId\u0028\u0029",
            "name": "getPosterId",
            "summary": "",
            "url": "classes/Entity-Season.html#method_getPosterId"
        },                {
            "fqsen": "\\Entity\\Season\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "s\u00E9lectionne\u0020les\u0020saisons",
            "url": "classes/Entity-Season.html#method_findById"
        },                {
            "fqsen": "\\Entity\\TvShow",
            "name": "TvShow",
            "summary": "",
            "url": "classes/Entity-TvShow.html"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getId"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getName"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetOverview\u0028\u0029",
            "name": "getOverview",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getOverview"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetOriginalName\u0028\u0029",
            "name": "getOriginalName",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getOriginalName"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetHomePage\u0028\u0029",
            "name": "getHomePage",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getHomePage"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetPosterId\u0028\u0029",
            "name": "getPosterId",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_getPosterId"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetId\u0028\u0029",
            "name": "setId",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setId"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setName"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetOriginalName\u0028\u0029",
            "name": "setOriginalName",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setOriginalName"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetHomepage\u0028\u0029",
            "name": "setHomepage",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setHomepage"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetOverview\u0028\u0029",
            "name": "setOverview",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setOverview"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AsetPosterId\u0028\u0029",
            "name": "setPosterId",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_setPosterId"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "cherche\u0020la\u0020serie\u0020TV\u0020en\u0020fonction\u0020de\u0020l\u0027id",
            "url": "classes/Entity-TvShow.html#method_findById"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003AgetSeasons\u0028\u0029",
            "name": "getSeasons",
            "summary": "r\u00E9cup\u00E8re\u0020toutes\u0020les\u0020saisons\u0020de\u0020la\u0020series\u0020tv",
            "url": "classes/Entity-TvShow.html#method_getSeasons"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Entity-TvShow.html#method_delete"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "cr\u00E9e\u0020une\u0020s\u00E9ries\u0020tv",
            "url": "classes/Entity-TvShow.html#method_create"
        },                {
            "fqsen": "\\Entity\\TvShow\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "enregistre\u0020la\u0020documentation\u0020ou\u0020la\u0020cr\u00E9ation",
            "url": "classes/Entity-TvShow.html#method_save"
        },                {
            "fqsen": "\\Html\\AppWebPage",
            "name": "AppWebPage",
            "summary": "",
            "url": "classes/Html-AppWebPage.html"
        },                {
            "fqsen": "\\Html\\AppWebPage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-AppWebPage.html#method___construct"
        },                {
            "fqsen": "\\Html\\AppWebPage\u003A\u003AtoHTML\u0028\u0029",
            "name": "toHTML",
            "summary": "",
            "url": "classes/Html-AppWebPage.html#method_toHTML"
        },                {
            "fqsen": "\\Html\\Form\\TvShowForm",
            "name": "TvShowForm",
            "summary": "",
            "url": "classes/Html-Form-TvShowForm.html"
        },                {
            "fqsen": "\\Html\\Form\\TvShowForm\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-Form-TvShowForm.html#method___construct"
        },                {
            "fqsen": "\\Html\\Form\\TvShowForm\u003A\u003AgetTvShow\u0028\u0029",
            "name": "getTvShow",
            "summary": "",
            "url": "classes/Html-Form-TvShowForm.html#method_getTvShow"
        },                {
            "fqsen": "\\Html\\Form\\TvShowForm\u003A\u003AgetHtmlForm\u0028\u0029",
            "name": "getHtmlForm",
            "summary": "",
            "url": "classes/Html-Form-TvShowForm.html#method_getHtmlForm"
        },                {
            "fqsen": "\\Html\\Form\\TvShowForm\u003A\u003AsetEntityFromQueryString\u0028\u0029",
            "name": "setEntityFromQueryString",
            "summary": "",
            "url": "classes/Html-Form-TvShowForm.html#method_setEntityFromQueryString"
        },                {
            "fqsen": "\\Html\\StringEscaper",
            "name": "StringEscaper",
            "summary": "",
            "url": "classes/Html-StringEscaper.html"
        },                {
            "fqsen": "\\Html\\StringEscaper\u003A\u003AescapeString\u0028\u0029",
            "name": "escapeString",
            "summary": "",
            "url": "classes/Html-StringEscaper.html#method_escapeString"
        },                {
            "fqsen": "\\Html\\StringEscaper\u003A\u003AstripTagsAndTrim\u0028\u0029",
            "name": "stripTagsAndTrim",
            "summary": "",
            "url": "classes/Html-StringEscaper.html#method_stripTagsAndTrim"
        },                {
            "fqsen": "\\Html\\WebPage",
            "name": "WebPage",
            "summary": "",
            "url": "classes/Html-WebPage.html"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Html-WebPage.html#method___construct"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetHead\u0028\u0029",
            "name": "getHead",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getHead"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getTitle"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getBody"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_setTitle"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendToHead\u0028\u0029",
            "name": "appendToHead",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendToHead"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendContent\u0028\u0029",
            "name": "appendContent",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendContent"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendCss\u0028\u0029",
            "name": "appendCss",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendCss"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendCssUrl\u0028\u0029",
            "name": "appendCssUrl",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendCssUrl"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendJs\u0028\u0029",
            "name": "appendJs",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendJs"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AappendJsUrl\u0028\u0029",
            "name": "appendJsUrl",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_appendJsUrl"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AgetLastModification\u0028\u0029",
            "name": "getLastModification",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_getLastModification"
        },                {
            "fqsen": "\\Html\\WebPage\u003A\u003AtoHTML\u0028\u0029",
            "name": "toHTML",
            "summary": "",
            "url": "classes/Html-WebPage.html#method_toHTML"
        },                {
            "fqsen": "\\ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6",
            "name": "ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6.html"
        },                {
            "fqsen": "\\ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6\u003A\u003AloadClassLoader\u0028\u0029",
            "name": "loadClassLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6.html#method_loadClassLoader"
        },                {
            "fqsen": "\\ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6\u003A\u003AgetLoader\u0028\u0029",
            "name": "getLoader",
            "summary": "",
            "url": "classes/ComposerAutoloaderInit6611ac8ed49cdaedea14c00e52838ac6.html#method_getLoader"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6",
            "name": "ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6\u003A\u003AgetInitializer\u0028\u0029",
            "name": "getInitializer",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6.html#method_getInitializer"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6\u003A\u003A\u0024fallbackDirsPsr4",
            "name": "fallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6.html#property_fallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6\u003A\u003A\u0024classMap",
            "name": "classMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ComposerStaticInit6611ac8ed49cdaedea14c00e52838ac6.html#property_classMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader",
            "name": "ClassLoader",
            "summary": "ClassLoader\u0020implements\u0020a\u0020PSR\u002D0,\u0020PSR\u002D4\u0020and\u0020classmap\u0020class\u0020loader.",
            "url": "classes/Composer-Autoload-ClassLoader.html"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method___construct"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixes\u0028\u0029",
            "name": "getPrefixes",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixes"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetPrefixesPsr4\u0028\u0029",
            "name": "getPrefixesPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getPrefixesPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirs\u0028\u0029",
            "name": "getFallbackDirs",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirs"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetFallbackDirsPsr4\u0028\u0029",
            "name": "getFallbackDirsPsr4",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getFallbackDirsPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetClassMap\u0028\u0029",
            "name": "getClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddClassMap\u0028\u0029",
            "name": "addClassMap",
            "summary": "",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addClassMap"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_add"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AaddPsr4\u0028\u0029",
            "name": "addPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\u0020either\nappending\u0020or\u0020prepending\u0020to\u0020the\u0020ones\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_addPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D0\u0020directories\u0020for\u0020a\u0020given\u0020prefix,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020prefix.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_set"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetPsr4\u0028\u0029",
            "name": "setPsr4",
            "summary": "Registers\u0020a\u0020set\u0020of\u0020PSR\u002D4\u0020directories\u0020for\u0020a\u0020given\u0020namespace,\nreplacing\u0020any\u0020others\u0020previously\u0020set\u0020for\u0020this\u0020namespace.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setPsr4"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetUseIncludePath\u0028\u0029",
            "name": "setUseIncludePath",
            "summary": "Turns\u0020on\u0020searching\u0020the\u0020include\u0020path\u0020for\u0020class\u0020files.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetUseIncludePath\u0028\u0029",
            "name": "getUseIncludePath",
            "summary": "Can\u0020be\u0020used\u0020to\u0020check\u0020if\u0020the\u0020autoloader\u0020uses\u0020the\u0020include\u0020path\u0020to\u0020check\nfor\u0020classes.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getUseIncludePath"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetClassMapAuthoritative\u0028\u0029",
            "name": "setClassMapAuthoritative",
            "summary": "Turns\u0020off\u0020searching\u0020the\u0020prefix\u0020and\u0020fallback\u0020directories\u0020for\u0020classes\nthat\u0020have\u0020not\u0020been\u0020registered\u0020with\u0020the\u0020class\u0020map.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AisClassMapAuthoritative\u0028\u0029",
            "name": "isClassMapAuthoritative",
            "summary": "Should\u0020class\u0020lookup\u0020fail\u0020if\u0020not\u0020found\u0020in\u0020the\u0020current\u0020class\u0020map\u003F",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_isClassMapAuthoritative"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AsetApcuPrefix\u0028\u0029",
            "name": "setApcuPrefix",
            "summary": "APCu\u0020prefix\u0020to\u0020use\u0020to\u0020cache\u0020found\/not\u002Dfound\u0020classes,\u0020if\u0020the\u0020extension\u0020is\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_setApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetApcuPrefix\u0028\u0029",
            "name": "getApcuPrefix",
            "summary": "The\u0020APCu\u0020prefix\u0020in\u0020use,\u0020or\u0020null\u0020if\u0020APCu\u0020caching\u0020is\u0020not\u0020enabled.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getApcuPrefix"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Registers\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_register"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003Aunregister\u0028\u0029",
            "name": "unregister",
            "summary": "Unregisters\u0020this\u0020instance\u0020as\u0020an\u0020autoloader.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_unregister"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AloadClass\u0028\u0029",
            "name": "loadClass",
            "summary": "Loads\u0020the\u0020given\u0020class\u0020or\u0020interface.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_loadClass"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AfindFile\u0028\u0029",
            "name": "findFile",
            "summary": "Finds\u0020the\u0020path\u0020to\u0020the\u0020file\u0020where\u0020the\u0020class\u0020is\u0020defined.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_findFile"
        },                {
            "fqsen": "\\Composer\\Autoload\\ClassLoader\u003A\u003AgetRegisteredLoaders\u0028\u0029",
            "name": "getRegisteredLoaders",
            "summary": "Returns\u0020the\u0020currently\u0020registered\u0020loaders\u0020keyed\u0020by\u0020their\u0020corresponding\u0020vendor\u0020directories.",
            "url": "classes/Composer-Autoload-ClassLoader.html#method_getRegisteredLoaders"
        },                {
            "fqsen": "\\Composer\\InstalledVersions",
            "name": "InstalledVersions",
            "summary": "This\u0020class\u0020is\u0020copied\u0020in\u0020every\u0020Composer\u0020installed\u0020project\u0020and\u0020available\u0020to\u0020all",
            "url": "classes/Composer-InstalledVersions.html"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackages\u0028\u0029",
            "name": "getInstalledPackages",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020which\u0020are\u0020present,\u0020either\u0020by\u0020being\u0020installed,\u0020replaced\u0020or\u0020provided",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackages"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstalledPackagesByType\u0028\u0029",
            "name": "getInstalledPackagesByType",
            "summary": "Returns\u0020a\u0020list\u0020of\u0020all\u0020package\u0020names\u0020with\u0020a\u0020specific\u0020type\u0020e.g.\u0020\u0027library\u0027",
            "url": "classes/Composer-InstalledVersions.html#method_getInstalledPackagesByType"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AisInstalled\u0028\u0029",
            "name": "isInstalled",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020is\u0020installed",
            "url": "classes/Composer-InstalledVersions.html#method_isInstalled"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Asatisfies\u0028\u0029",
            "name": "satisfies",
            "summary": "Checks\u0020whether\u0020the\u0020given\u0020package\u0020satisfies\u0020a\u0020version\u0020constraint",
            "url": "classes/Composer-InstalledVersions.html#method_satisfies"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersionRanges\u0028\u0029",
            "name": "getVersionRanges",
            "summary": "Returns\u0020a\u0020version\u0020constraint\u0020representing\u0020all\u0020the\u0020range\u0028s\u0029\u0020which\u0020are\u0020installed\u0020for\u0020a\u0020given\u0020package",
            "url": "classes/Composer-InstalledVersions.html#method_getVersionRanges"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetPrettyVersion\u0028\u0029",
            "name": "getPrettyVersion",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getPrettyVersion"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getReference"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetInstallPath\u0028\u0029",
            "name": "getInstallPath",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getInstallPath"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRootPackage\u0028\u0029",
            "name": "getRootPackage",
            "summary": "",
            "url": "classes/Composer-InstalledVersions.html#method_getRootPackage"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetRawData\u0028\u0029",
            "name": "getRawData",
            "summary": "Returns\u0020the\u0020raw\u0020installed.php\u0020data\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003AgetAllRawData\u0028\u0029",
            "name": "getAllRawData",
            "summary": "Returns\u0020the\u0020raw\u0020data\u0020of\u0020all\u0020installed.php\u0020which\u0020are\u0020currently\u0020loaded\u0020for\u0020custom\u0020implementations",
            "url": "classes/Composer-InstalledVersions.html#method_getAllRawData"
        },                {
            "fqsen": "\\Composer\\InstalledVersions\u003A\u003Areload\u0028\u0029",
            "name": "reload",
            "summary": "Lets\u0020you\u0020reload\u0020the\u0020static\u0020array\u0020from\u0020another\u0020file",
            "url": "classes/Composer-InstalledVersions.html#method_reload"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Entity\\Collection",
            "name": "Collection",
            "summary": "",
            "url": "namespaces/entity-collection.html"
        },                {
            "fqsen": "\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/entity.html"
        },                {
            "fqsen": "\\Entity\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/entity-exception.html"
        },                {
            "fqsen": "\\Html",
            "name": "Html",
            "summary": "",
            "url": "namespaces/html.html"
        },                {
            "fqsen": "\\Html\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/html-form.html"
        },                {
            "fqsen": "\\Composer\\Autoload",
            "name": "Autoload",
            "summary": "",
            "url": "namespaces/composer-autoload.html"
        },                {
            "fqsen": "\\Composer",
            "name": "Composer",
            "summary": "",
            "url": "namespaces/composer.html"
        }            ]
);
